language: python

services: sqlite

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO="django==1.7"
    - DJANGO="django==1.6.5"
    - DJANGO="django==1.5.8"
    - DJANGO="django==1.4.13"

install:
    - pip install $DJANGO
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt

script:
    - ./runtests.py

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="django==1.7"
    - python: "3.2"
      env: DJANGO="django==1.4.13"
    - python: "3.3"
      env: DJANGO="django==1.4.13"
    - python: "3.4"
      env: DJANGO="django==1.4.13"
